#!/opt/pwn.college/python
import sys

sys.path.append('/challenge')

def print_flag():
    try:
        with open("/flag", "r") as f:
            print(f.read())
    except FileNotFoundError:
        print("Error: Flag file not found.")

def main():

    # Open their code
    try:
        with open(sys.argv[1], 'r') as fObj:
            code = fObj.readlines()
    except FileNotFoundError:
        print(f"File '{sys.argv[1]}' not found!")
        sys.exit(1)

    # Check for 'inputs'
    if len([x for x in code if 'input' in x]) != 5:
        print("It looks like you didn't use 5 'input' function calls.")
        sys.exit(1)

    if len([x for x in code if 'int' in x]) < 5:
        print("It looks like you didn't typecast all your input to integers.") 
        sys.exit(1)

    # Check for 'print'
    if len([x for x in code if 'print' in x]) < 1:
        print("It looks like you didn't 'print' anything out.")
        sys.exit(1)

    print_flag()


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: run <user_script.py>")
        sys.exit(1)

    main()
