#!/opt/pwn.college/python

from pacePythonTester.ExecutionAgent import ExecutionAgent as ex
import sys
import re

def print_flag():
    try:
        with open("/flag") as f:
            print(f.read())
    except FileNotFoundError:
        print("Error: Flag file not found.")

def run_and_check_script(user_script_path):

    # Run their program
    stdout, stderr = ex.run(user_script_path)

    # Set up to match all cases of Hello World!
    text = re.compile('^hello world!?$', re.IGNORECASE)
    if not text.match(stdout.strip()):
        print(f"Error: Make sure that you are printing 'Hello World!' exactly!")
        exit()

    print_flag()


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: run <user_script.py>")
        sys.exit(1)

    user_script_path = sys.argv[1]
    run_and_check_script(user_script_path)
