#!/opt/pwn.college/python
import socket

with open('/flag', 'r') as fObj:
    flag = fObj.read()

def main():
    # Create server
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind(('localhost', 1337))
    s.listen(3)

    print("Socket server is set up!")
    print("Connect to me at '127.0.0.1' on port 1337!")
    while True:
        client, addr = s.accept()
        buf = client.recv(1024)
        if len(buf) > 0:
            client.send(flag.encode())

if __name__ == "__main__":
    main()
