#!/opt/pwn.college/python
import socket
from time import sleep

with open('/flag', 'r') as fObj:
    flag = fObj.read()

def main():
    # Create server
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    z = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    
    try:
        s.connect(('127.0.0.1', 1337))
    except socket.error as e:
        print(f"Socket Error: {e}. Failed to connect!")

    try:
        s.send('First connection\n'.encode())
    except BrokenPipeError:
        print("Failed to send data to server.")

    print("First request was sent to your server!")

    s.close()

    sleep(2)

    try:
        z.connect(('127.0.0.1', 1337))
    except socket.error as e:
        print(f"Socket Error: {e}. Failed to connect!")

    try:
        z.send(flag.encode())
    except BrokenPipeError:
        print("Failed to send data to server.")

    print("Flag was sent over to your server!")

    z.close()

if __name__ == "__main__":
    main()
