#!/opt/pwn.college/python
import sys
import os
import re

sys.path.append('/challenge')
from pacePythonTester import ExecutionAgent as ex

def print_flag():
    try:
        with open("/flag", "r") as f:
            print(f.read())
    except FileNotFoundError:
        print("Error: Flag file not found.")

def run_and_check_script(user_script_path):

    for a,b in [(1,2),(2,1),(1,1)]:
        less = re.compile('less than', re.IGNORECASE)
        greater = re.compile('greater than', re.IGNORECASE)
        equal = re.compile('equal to', re.IGNORECASE)

        # Track all of them so that the user doesn't just print all the answers
        incorrect = [less, greater, equal]

        if a < b:
            text = incorrect.pop(0)
        elif a > b:
            text = incorrect.pop(1)
        else:
            text = incorrect.pop(2)

        # Run their program with the test case
        try:
            stdout, stderr = ex.run(user_script_path, input=f"{a}\n{b}\n")
        except TypeError as e:
            """ Issue with noneType return """
            print("Error:", e)
            exit()

        if not re.search(text, stdout.strip()):
            print(f"Error: Make sure that you are printing '{text}' exactly!")
            exit()

        # This is to ensure that they are only printing one answer for each itteration of the program 
        for possible in incorrect:
            if re.search(possible, stdout.strip()):
                print(f"Error: Make sure to only print 'less than' 'greater than' or 'equal to' for a set of numbers")
                exit()

    print_flag()


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: run <user_script.py>")
        sys.exit(1)

    user_script_path = sys.argv[1]
    run_and_check_script(user_script_path)
