#!/opt/pwn.college/python
import sys
import os
import re

sys.path.append('/challenge')
from pacePythonTester import ExecutionAgent as ex

def print_flag():
    try:
        with open("/flag", "r") as f:
            print(f.read())
    except FileNotFoundError:
        print("Error: Flag file not found.")

def get_file_path(file_name):
    """ Get the full path to a file located in the current working directory. """
    cwd = os.getcwd()  # Get the current working directory
    full_path = os.path.join(cwd, file_name)  # Construct the full path

    if os.path.isfile(full_path):
        return full_path
    else:
        return None

def check_script(user_script_path):

    # Calculate file path if not given
    if '/' not in user_script_path:
        user_script_path = get_file_path(user_script_path)

    # Verify the file exists
    if not full_path:
        print("Error: Couldn't find your python script")
        exit()

    vars = ex.get_variables(user_script_path)
    if len(vars) >= 3:
        print_flag()
    else:
        print("Error: Make sure to define at least 3 variables in your script!")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: run <user_script.py>")
        sys.exit(1)

    user_script_path = sys.argv[1]
    check_script(user_script_path)
