#!/usr/bin/exec-suid --real -- /usr/bin/python -I

from os.path import exists

if not exists('/home/hacker/bee_movie_script.txt'):
	print("Couldn't find file '/home/hacker/bee_movie_script.txt'")
	exit(0)

with open('/home/hacker/bee_movie_script.txt', 'r') as fObj:
	data = fObj.read()

if data.lower().strip() != "according to all known laws of aviation...":
	print("It appears that the data you wrote doesn't match up!")
	exit(0)

print("Congratulations!")
with open('/flag', 'r') as fObj:
	print(fObj.read())
