#!/opt/pwn.college/python
import socket

with open('/flag', 'r') as fObj:
    flag = fObj.read()

def main():
    # Create server
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    
    try:
        s.connect(('127.0.0.1', 1337))
    except socket.error as e:
        print(f"Socket Error: {e}. Failed to connect!")

    s.send(flag.encode())

    print("Flag was sent over to your server!")

    s.close()

if __name__ == "__main__":
    main()
