#!/opt/pwn.college/python
import sys
import os
import re

sys.path.append('/challenge')
from pacePythonTester import ExecutionAgent as ex

def print_flag():
    try:
        with open("/flag", "r") as f:
            print(f.read())
    except FileNotFoundError:
        print("Error: Flag file not found.")

def run_and_check_script(user_script_path):

    for a,b in [(90,95),(15,5)]:

        # Track all of them so that the user doesn't just print all the answers
        incorrect = [re.compile('Honors Student', re.IGNORECASE),
                    re.compile('Failing Student', re.IGNORECASE)]

        # Determine the correct answer
        if a >= 85 and b >= 90:
            correct = incorrect.pop(0)
        else:
            correct = incorrect.pop(1)

        # Run their program with the test case
        try:
            stdout, stderr = ex.run(user_script_path, input=f"{a}\n{b}\n")
        except TypeError as e:
            """ Issue with noneType return """
            print("Error:", e)
            exit()

        if not stdout.strip().search(correct):
            print(f"Error: Make sure that you are printing '{correct}' exactly!")
            exit()

        # This is to ensure that they are only printing one answer for each itteration of the program 
        for possible in incorrect:
            if stdout.strip().search(possible):
                print(f"Error: Make sure to only print the correct response")
                exit()

    print_flag()


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: run <user_script.py>")
        sys.exit(1)

    user_script_path = sys.argv[1]
    run_and_check_script(user_script_path)
